# Generated by Django 5.0.14 on 2026-09-17 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Discover Your Style', max_length=150)),
                ('subtitle', models.CharField(default='Premium Fashion For Every Occasion', max_length=250)),
                ('image', models.ImageField(upload_to='hero/')),
                ('primary_button_text', models.CharField(default='Shop Men', max_length=50)),
                ('primary_button_link', models.CharField(default='/products/men/', max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, default='Shop Women', max_length=50)),
                ('secondary_button_link', models.CharField(blank=True, default='/products/women/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Tahir Rafique Cloth House', max_length=150)),
                ('tagline', models.CharField(default='Premium Fashion For Every Occasion', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('whatsapp_number', models.CharField(default='032857948', help_text='Local Pakistani number, e.g. 032857948. Converted automatically for WhatsApp links.', max_length=20)),
                ('support_phone', models.CharField(default='032857948', max_length=20)),
                ('email', models.EmailField(default='info@tahirrafiqueclothhouse.com', max_length=254)),
                ('address', models.CharField(default='Blue Area, Islamabad, Pakistan', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com')),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=250, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=5000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_symbol', models.CharField(default='Rs.', max_length=10)),
                ('announcement_text', models.CharField(blank=True, default='Free Delivery on Orders Above Rs. 5,000', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
